### ISSUE TITLE
Auth::attempt() gives "User is unverified" because wrong fieldname in db-schema

### ISSUE THREAD

**Issue by cahva** [Toddish/Verify#1]
In the database's users table there is fieldname "confirmed" but Verify library is looking for "verified" fieldname. Fix is to either change the schema "confirmed" -> "verified" field or change the "verified" to "confirmed" in the Verify library.

**Comment by doginthehat** [comment]
I _confirm_, this is a _verified_ bug.

(sorry, had to.. it's definitely a bug though :)

**Comment by Toddish** [comment]
That'll teach me to code when I'm tired! Cheers, fixed :)

**Comment by doginthehat** [comment]
@Toddish 

Thanks for fixing. 

Would probably have been better to add a separate migration file for the patch otherwise the database on existing installations wouldn't be patched

**Comment by Toddish** [comment]
I wanted to do that, but I couldn't see a way to alter columns using the Schema class. I've now realised I can. I'll change it.

**Comment by Toddish** [comment]
Hmm, it seems the only way I can do this using the Schema class is to drop then create the column, which of course would lose all the data in the initial column.

I think, as the bundle is still young and the install base probably very low, I'll just leave the edited initial migration file. I'm sure the few people that have installed it can just change the column themselves.

I'll leave it a few days to see if anyone has any other suggestions. If not, I might just close the issue.

**Comment by doginthehat** [comment]
@Toddish Yes, I agree, probably not worth the hassle at this early stage of the development :)

**Comment by bgallagh3r** [comment]
Um.. I hate to say it, but I'm building an app using this auth system.  And I gotta say, if this is how you guys are going to fix bugs by dropping databases, I don't think I'll continue using this system.  I love it's simplicity, but you have NO documentation stating this "fix" in the readme for users who are upgrading versions.  

That's not what I would call best practice.  If you're going to go the short and easy fix route at least document it for your users in a changelog or something.

**Comment by Toddish** [comment]
That's a fair point. As stated above though, the fix would be different if I could alter columns using the Schema class.

And to be honest, the fix was made days after the bundle was released, and I didn't think many people would even be using it.

I'll be adding a changelog in the next few days when I release the next update, along with upgrade instructions. I'll also be adding more substantial docs on my site eventually.

For now, changing one column in a database isn't exactly a big deal :)
