### ISSUE TITLE
Documentation Incorrect

### ISSUE THREAD

**Issue by haydenhancock** [Toddish/Verify#11]
http://paste.laravel.com/6zt

**Comment by Toddish** [comment]
Cheers haydenhancock, I'll close this for now and leave #12 open.

**Comment by dshoreman** [comment]
#12 is just a side-effect of posting the fix for this issue (not that it matters). I have no idea why Github creates a new issue even if I reference one that already exists =/

**Comment by haydenhancock** [comment]
Thanks Toddish!
