### ISSUE TITLE
Column description should be nullable

### ISSUE THREAD

**Issue by allartk** [Toddish/Verify#19]
Running the migrate command returns
<code>
$ php artisan migrate verify
SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "description" violates not-null constraint

SQL: INSERT INTO "roles" ("name", "level") VALUES (?, ?)

Bindings: array (
  0 => 'Super Admin',
  1 => 10,
)
</code>

**Comment by Toddish** [comment]
Odd, the migrations has always worked for me. It makes sense to make it nullable anyway.
