### ISSUE TITLE
New user with existing Role

### ISSUE THREAD

**Issue by xtrasmal** [Toddish/Verify#22]
Hi there,

In de documentation I read the following:

``` php
// Create a new Permission
$permission = new \Verify\Models\Permission;
$permission->name = 'delete_user';
$permission->save();

// Create a new Role
$role = new Verify\Models\Role;
$role->name = 'Moderator';
$role->level = 7;
$role->save();

// Assign the Permission to the Role
$role->permissions()->sync(array($permission->id));

// Create a new User
$user = new \Verify\Models\User;
$user->username = 'Todd';
$user->email = 'todd@toddish.co.uk';
$user->password = 'password'; // This is automatically salted and encrypted
$user->save();

// Assign the Role to the User
$user->roles()->sync(array($role->id));
```

I created the roles and the permissions, so that's that.
Now when I create a new user.. how would I assign a existing role and/or 
permission?

I would think I need to do something like

``` php
$role = \Verify\Models\Role::where_level(1)->first();
```

This works, but I do not know if it is the right way to go.

**Comment by Toddish** [comment]
Hey, 

That's pretty much spot on.

I'd personally load the role by the id, rather than the level, in case you have two roles with the same level, but it's generally the correct idea.
