### ISSUE TITLE
Grab user with model

### ISSUE THREAD

**Issue by Thijmen** [Toddish/Verify#26]
Hi,

I have a model, and I have this function:

``` php
<?php
class Ticketentry extends Eloquent {
    public function ticket()
    {
        return $this->has_one('Ticket');
    }

    public function user()
    {
        return $this->has_one('Verify\Models\User','id');
    }
}
```

Yet, when I grab a Ticketentry, and I try to do `$ticketentry->user->username`, it doesn't work. What am I doing wrong?

I get this error:

```
Trying to get property of non-object
```

**Comment by Thijmen** [comment]
Wrote a quick dirty method in my model, but I wonder if there's another solution than this one;

``` php
public function user()
    {
        return Auth::retrieve($this->verify_user_id);
    }
```

**Comment by Toddish** [comment]
Hey, 

I think there might be a problem with your model relationships. If you're using verify_user_id as your foreign key, you need to pass that into the relationship.

Try that, and if it doesn't work, post your DB schema and I'll see if I can help :)
