### ISSUE TITLE
Access model in models folder

### ISSUE THREAD

**Issue by Thijmen** [Toddish/Verify#27]
Hi,

I am expanding the `User` class of Verify to make some changes for my project.
I want to access a model that I have, named `Project`.

Which namespace do I need to use? It's in the default `application/models` folder.

**Comment by Toddish** [comment]
Hey, 

To extend the Verify User model, you'll need to do something like this:

``` php
use Verify\Models\User as VerifyUser;

class User extends VerifyUser {}
```

**Comment by Thijmen** [comment]
And how do I extend the Auth:: object?
So that I can do Auth::can_access('project'), which would return a true or false depending on the current logged in user.

**Comment by Toddish** [comment]
If you extend the user model, the public functions will be available via the Auth facade, so just add it in there.
