### ISSUE TITLE
updating user doesn't hash the password

### ISSUE THREAD

**Issue by codivist** [Toddish/Verify#28]
My User model extends Verify\Models\User, and most everything is working awesome. Thanks for this bundle.

One issue I have is when I try to run an update on the user (i.e. changing the password) everything seems to work fine, but the password is not getting hashed or salted, it is just inserted as plain text.

```
User::where_id(Input::get('user_id'))
->update(array(
        'password'   => Input::get('password'),
    'updated_at' => date('Y-m-d g:i:s'),
));
```

**Comment by Toddish** [comment]
I think it's because that's using fluent, not eloquent.

Try:

``` php
$user = User:where_id(Input::get('user_id'))->first();
$user->password = Input::get('password');
$user->save();
```

**Comment by codivist** [comment]
That was it. Thanks for your quick help.
