### ISSUE TITLE
Prefix for db tables

### ISSUE THREAD

**Issue by doginthehat** [Toddish/Verify#3]
@Toddish A feature request:

Could there be some sort of config setting added that would allow to prefix the db_tables?

On a big project it would make it clearer which tables are from what.

**Comment by Toddish** [comment]
Sounds like a good idea. I'll also edit the initial migration to create it with a prefix if one is specified.

**Comment by doginthehat** [comment]
@Toddish Cool, thanks. Maybe it can have a default one, most people will probably be happy to leave it with the default.

Point of concern, changing prefix past the first setup would make the migration scripts impossible..

**Comment by Toddish** [comment]
Should be implemented in v2
