### ISSUE TITLE
General error: 1 near "CONSTRAINT": syntax error

### ISSUE THREAD

**Issue by mplx** [Toddish/Verify#4]
Installing on a blank sqlite3 database....

$ php artisan migrate verify
SQLSTATE[HY000]: General error: 1 near "CONSTRAINT": syntax error

SQL: ALTER TABLE "users" ADD CONSTRAINT users_role_id_foreign FOREIGN KEY ("role
_id") REFERENCES "roles" ("id")

Bindings: array (
)

```
```

**Comment by Toddish** [comment]
Odd, it's just using the migrations.

I don't have the internet at the moment (I'm in the process of moving house), so I won't be able to test/fix this for a few weeks.

Feel free to make a pull request if you figure it out in the meantime :)

**Comment by mplx** [comment]
Thanks for your reply! :)

I'm sorry I've bothered you with this - it's working like a charm with mysql, and as I've found out the problem is related to sqlite - foreign keys have to be created with the CREATE TABLE statement and not via ALTER TABLE (see http://www.sqlite.org/foreignkeys.html).

So either my php's sqlite library is not compiled with foreign key support enabled (I'm currently using php from cygwinports) or it's a problem how lavarel deals with sqlite databases...

**Comment by Toddish** [comment]
Ah OK. Glad you got it sorted!
