### ISSUE TITLE
General error: 1005 at artisan migrate verify

### ISSUE THREAD

**Issue by jeroengerits** [Toddish/Verify#5]
Just created a fresh and clean Laravel installation and installed the verify bundle. 

However if i migrate verify the response is;

SQLSTATE[HY000]: General error: 1005 Can't create table 'mydb.#sql-3e3_e0' (errno: 150)
SQL: ALTER TABLE `users` ADD CONSTRAINT users_role_id_foreign FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`)

My own migration work great, so i guess something is 'broken'?

**Comment by Toddish** [comment]
Hey, what database are you using (SQLite, MySQL etc), and what version of Laravel?

It looks similar to this issue : https://github.com/Toddish/Verify/issues/4

**Comment by pywebdesign** [comment]
can you provide a SQL schema file? BTW I use MySQL

**Comment by Toddish** [comment]
Ah, it happened MySQL? What version?

I did used to provide an SQL schema file, but people got confused with it so I took it out for clarity. You can find the old file here:

https://github.com/Toddish/Verify/blob/3448b266dcfdcd49b721cc8f48b411fd680ec847/verify.sql

I don't _think_ I've done any SQL changes since I took it out, but if I have and you have trouble with it, let me know.

**Comment by dshoreman** [comment]
I too am getting this error when I try to migrate Verify on a new project, but I know it worked fine last time I tried. Going through, it doesn't look like there have been any changes to Verify (it seems I caught it shortly after the most recent commit).

The project where Verify migrated fine was running Laravel 3.2.3, so there must've been something changed between that version and 3.2.7 that's broken it. I'm still relatively new to Laravel but if I find anything along the way I'll post back later.

Update: running 'SHOW ENGINE INNODB STATUS;' in mysql cli gets this every-so-slightly more helpful message:

```
------------------------
LATEST FOREIGN KEY ERROR
------------------------
120905 14:16:02 Error in foreign key constraint of table tekkitcalc/#sql-8f2_9:
 FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`):
Cannot find an index in the referenced table where the
referenced columns appear as the first columns, or column types
in the table and the referenced table do not match for constraint.
Note that the internal storage type of ENUM and SET changed in
tables created with >= InnoDB-4.1.12, and such columns in old tables
cannot be referenced by such columns in new tables.
See http://dev.mysql.com/doc/refman/5.5/en/innodb-foreign-key-constraints.html
for correct foreign key definition.
```

### Final Update:

I have no idea what I did last time to make it work, I must've deleted the index/relation parts and done those manually. Either way, it's all working for me now. Long story short: Laravel adds unsigned for auto increment, so it needs it for relationships too.

**Comment by nickewansmith** [comment]
I still get this error after a fresh install of laravel with a fresh db and the latest merge that claims to fix this issue.

SQLSTATE[HY000]: General error: 1005 Can't create table 'blackbizmall.#sql-90a_1b9dd' (errno: 150)

SQL: ALTER TABLE `users` ADD CONSTRAINT users_role_id_foreign FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`)

Bindings: array (
)

I am using InnoDB and MySql

I have installed verify before the present laravel release and there was no issue.

**Comment by Toddish** [comment]
Odd, I thought this was fixed.

What version of MySQL/PHP/Laravel are you using?

I've just done a fresh install on MySQL 5.5.20, PHP 5.3.10 and Laravel 3.2.10 and it worked fine.

**Comment by nickewansmith** [comment]
PHP Version 5.3.8
mysql  Ver 14.14 Distrib 5.5.17
Laravel 3.2.3 ?? (That's what the folder said, don't know where I got that from)

The migration runs successfully with 3.2.10

**Comment by Toddish** [comment]
Might be something's changed in the Laravel migration code since 3.2.3
then. (You can check your Laravel version by opening up public/index.php,
it should be in there as a comment at the top.)

I'll see if I can get some old copies of Laravel and try installing the
bundle.

I can then at least add a minimum required version to the readme.
