### ISSUE TITLE
got an error similar to the other issues

### ISSUE THREAD

**Issue by pywebdesign** [Toddish/Verify#6]
SQLSTATE[HY000]: General error: 1005 Can't create table 'verify-auth.#sql-920_4f
1' (errno: 150)

SQL: ALTER TABLE `users` ADD CONSTRAINT users_role_id_foreign FOREIGN KEY (`role
_id`) REFERENCES `roles` (`id`)

Bindings: array (
)

**Comment by Toddish** [comment]
Seems to be exactly the same issue, I'll close this one as it's a duplicate (#5)
