### ISSUE TITLE
No outstanding migrations.

### ISSUE THREAD

**Issue by grngc** [Toddish/Verify#9]
> php artisan bundle:install verify
> Successfully Installed!
> 
> php artisan migrate verify
> string(58) "SELECT `name` FROM `laravel_migrations` WHERE `bundle` = ?"
> No outstanding migrations.

The install script doesn't register the migration into the database.

**Comment by thetringuyen** [comment]
I think you need to register the bundle before run `php artisan migrate`

**Comment by Toddish** [comment]
Hey grngc.

As thetringuyen said, have you registered the bundle?

**Comment by grngc** [comment]
Yup, you're both right, I did not.
Sorry about that. I'm new to laravel ... and got a lot of issues when moving from testing (local windows) to production server. mainly because I had only php 5.2.9 on production server.

**Comment by Toddish** [comment]
No worries :)

Let me know if you need any more help with the bundle!
